### ISSUE TITLE
Post an order to 0x API

### ISSUE THREAD

**Issue by talegift** [build-finance/metric-frontend#18]
Let's keep the price (output amount) calculated automatically for now as-is.

When a user clicks on PLACE ORDER, we should post the valid order to the 0x API and reload the orderbook. The order should stay there even after reloading the page and also be shown to any other users on other devices - it should stay active in the 0x network.

Filling/matching orders is not a part of this task.

**Comment by SHA-2048** [comment]
The order book displays aggregated orders as explained in #13. So when submitting a new order, the new order would be included in the order book but it wouldn't be directly identifiable as it can be aggregated with other similar orders. 

Is this OK ?

**Comment by SHA-2048** [comment]
I've read the 0x documentation. I think I see how to do this. They have a helper library 0x.js I can use to ease the implem. But first I think there is some refactoring needed.

In order to progress on this, I will need to first refactor the swap.riot file. I think it needs to be split into several riot components to keep things manageable. Also it will be good to start using a bundler, I am thinking about using parcel (other option is webpack)

What do you think guys ? @talegift , @vfatouros , @nipa85 , @lepidotteri

**Comment by talegift** [comment]
If the complexity is too high now, feel free to break it down.

Indicating visually which order is ours in the order book is not necessary.
